name: test
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: run eslint
        uses: borales/actions-yarn@v4
        with:
          cmd: eslint
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build:dev